#Presentation Settings
sitename: CSS Radar
tagline: Mini Books For Front End Developers
desc: 現役フロントエンドデベロッパ、斉藤祐也がフロントエンドにまつわる情報やTipsを紹介。2〜3年は遅れているという日本のウェブをアップデートしたい。そんな思いで更新していきます
url: http://css.studiomohawk.com
#Deployment Settings
lessc: _less.js/bin/lessc
pygments:    true
markdown:    kramdown
permalink:   pretty
kramdown:
  auto_ids: false
exclude: LICENSE, README.markdown, Rakefile
